apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfgen
  labels:
    app: cfgen
    owner: devops
    system: ingress
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: cfgen
      owner: devops
      system: ingress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cfgen
        owner: devops
        system: ingress
    spec:
      serviceAccountName: cfgen-sa
      containers:
        - name: cfgen
          image: cfgen:latest
          imagePullPolicy: Always
          env:
            - name: WORKING_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFS_OUTPUT_PATH
              value: /confsout
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - mountPath: /confsout
              name: configs-volume
      volumes:
        - name: configs-volume
          emptyDir: {}