apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cfgen-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cfgen-sa
roleRef:
  kind: Role
  name: cfgen-role
  apiGroup: rbac.authorization.k8s.io