apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfgen-deployment
  labels:
    app: cfgen
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: cfgen
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cfgen
    spec:
      serviceAccountName: cfgen-sa
      containers:
        - name: cfgen
          image: cfgen:latest
          imagePullPolicy: Never
          env:
            - name: WORKING_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFS_OUTPUT_PATH
              value: /confsout
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /confsout
              name: configs-volume

        - name: bb
          image: busybox
          command: ['sleep', '3600']
          volumeMounts:
            - mountPath: /confsout
              name: configs-volume

      volumes:
        - name: configs-volume
          emptyDir: {}